// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.ActionVerification;
using ControlR.ApiClient.Api.AgentUpdate;
using ControlR.ApiClient.Api.AlertRules;
using ControlR.ApiClient.Api.Alerts;
using ControlR.ApiClient.Api.AuditLogs;
using ControlR.ApiClient.Api.Branding;
using ControlR.ApiClient.Api.ClientPortal;
using ControlR.ApiClient.Api.Credentials;
using ControlR.ApiClient.Api.DesktopPreview;
using ControlR.ApiClient.Api.DeviceFileSystem;
using ControlR.ApiClient.Api.DeviceGroups;
using ControlR.ApiClient.Api.DeviceTags;
using ControlR.ApiClient.Api.Devices;
using ControlR.ApiClient.Api.InstallerKeys;
using ControlR.ApiClient.Api.Inventory;
using ControlR.ApiClient.Api.Invites;
using ControlR.ApiClient.Api.JitAdmin;
using ControlR.ApiClient.Api.LogonTokens;
using ControlR.ApiClient.Api.Logout;
using ControlR.ApiClient.Api.Me;
using ControlR.ApiClient.Api.Metrics;
using ControlR.ApiClient.Api.PatchManagement;
using ControlR.ApiClient.Api.PersonalAccessTokens;
using ControlR.ApiClient.Api.Plugins;
using ControlR.ApiClient.Api.PublicRegistrationSettings;
using ControlR.ApiClient.Api.Roles;
using ControlR.ApiClient.Api.ScheduledTasks;
using ControlR.ApiClient.Api.ScriptExecutions;
using ControlR.ApiClient.Api.Scripts;
using ControlR.ApiClient.Api.ServerAlert;
using ControlR.ApiClient.Api.ServerLogs;
using ControlR.ApiClient.Api.ServerStats;
using ControlR.ApiClient.Api.SessionRecordings;
using ControlR.ApiClient.Api.Suggestions;
using ControlR.ApiClient.Api.SupportSessions;
using ControlR.ApiClient.Api.Tags;
using ControlR.ApiClient.Api.TenantSettings;
using ControlR.ApiClient.Api.Tenants;
using ControlR.ApiClient.Api.TestEmail;
using ControlR.ApiClient.Api.Ticketing;
using ControlR.ApiClient.Api.Toolbox;
using ControlR.ApiClient.Api.UserPreferences;
using ControlR.ApiClient.Api.UserRoles;
using ControlR.ApiClient.Api.UserServerSettings;
using ControlR.ApiClient.Api.UserTags;
using ControlR.ApiClient.Api.Users;
using ControlR.ApiClient.Api.VersionNamespace;
using ControlR.ApiClient.Api.Webhooks;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The actionVerification property</summary>
        public global::ControlR.ApiClient.Api.ActionVerification.ActionVerificationRequestBuilder ActionVerification
        {
            get => new global::ControlR.ApiClient.Api.ActionVerification.ActionVerificationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The agentUpdate property</summary>
        public global::ControlR.ApiClient.Api.AgentUpdate.AgentUpdateRequestBuilder AgentUpdate
        {
            get => new global::ControlR.ApiClient.Api.AgentUpdate.AgentUpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The alertRules property</summary>
        public global::ControlR.ApiClient.Api.AlertRules.AlertRulesRequestBuilder AlertRules
        {
            get => new global::ControlR.ApiClient.Api.AlertRules.AlertRulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The alerts property</summary>
        public global::ControlR.ApiClient.Api.Alerts.AlertsRequestBuilder Alerts
        {
            get => new global::ControlR.ApiClient.Api.Alerts.AlertsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auditLogs property</summary>
        public global::ControlR.ApiClient.Api.AuditLogs.AuditLogsRequestBuilder AuditLogs
        {
            get => new global::ControlR.ApiClient.Api.AuditLogs.AuditLogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The branding property</summary>
        public global::ControlR.ApiClient.Api.Branding.BrandingRequestBuilder Branding
        {
            get => new global::ControlR.ApiClient.Api.Branding.BrandingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clientPortal property</summary>
        public global::ControlR.ApiClient.Api.ClientPortal.ClientPortalRequestBuilder ClientPortal
        {
            get => new global::ControlR.ApiClient.Api.ClientPortal.ClientPortalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credentials property</summary>
        public global::ControlR.ApiClient.Api.Credentials.CredentialsRequestBuilder Credentials
        {
            get => new global::ControlR.ApiClient.Api.Credentials.CredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The desktopPreview property</summary>
        public global::ControlR.ApiClient.Api.DesktopPreview.DesktopPreviewRequestBuilder DesktopPreview
        {
            get => new global::ControlR.ApiClient.Api.DesktopPreview.DesktopPreviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deviceFileSystem property</summary>
        public global::ControlR.ApiClient.Api.DeviceFileSystem.DeviceFileSystemRequestBuilder DeviceFileSystem
        {
            get => new global::ControlR.ApiClient.Api.DeviceFileSystem.DeviceFileSystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deviceGroups property</summary>
        public global::ControlR.ApiClient.Api.DeviceGroups.DeviceGroupsRequestBuilder DeviceGroups
        {
            get => new global::ControlR.ApiClient.Api.DeviceGroups.DeviceGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::ControlR.ApiClient.Api.Devices.DevicesRequestBuilder Devices
        {
            get => new global::ControlR.ApiClient.Api.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deviceTags property</summary>
        public global::ControlR.ApiClient.Api.DeviceTags.DeviceTagsRequestBuilder DeviceTags
        {
            get => new global::ControlR.ApiClient.Api.DeviceTags.DeviceTagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installerKeys property</summary>
        public global::ControlR.ApiClient.Api.InstallerKeys.InstallerKeysRequestBuilder InstallerKeys
        {
            get => new global::ControlR.ApiClient.Api.InstallerKeys.InstallerKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The inventory property</summary>
        public global::ControlR.ApiClient.Api.Inventory.InventoryRequestBuilder Inventory
        {
            get => new global::ControlR.ApiClient.Api.Inventory.InventoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Invites property</summary>
        public global::ControlR.ApiClient.Api.Invites.InvitesRequestBuilder Invites
        {
            get => new global::ControlR.ApiClient.Api.Invites.InvitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jitAdmin property</summary>
        public global::ControlR.ApiClient.Api.JitAdmin.JitAdminRequestBuilder JitAdmin
        {
            get => new global::ControlR.ApiClient.Api.JitAdmin.JitAdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logonTokens property</summary>
        public global::ControlR.ApiClient.Api.LogonTokens.LogonTokensRequestBuilder LogonTokens
        {
            get => new global::ControlR.ApiClient.Api.LogonTokens.LogonTokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Logout property</summary>
        public global::ControlR.ApiClient.Api.Logout.LogoutRequestBuilder Logout
        {
            get => new global::ControlR.ApiClient.Api.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Me property</summary>
        public global::ControlR.ApiClient.Api.Me.MeRequestBuilder Me
        {
            get => new global::ControlR.ApiClient.Api.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metrics property</summary>
        public global::ControlR.ApiClient.Api.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::ControlR.ApiClient.Api.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The patchManagement property</summary>
        public global::ControlR.ApiClient.Api.PatchManagement.PatchManagementRequestBuilder PatchManagement
        {
            get => new global::ControlR.ApiClient.Api.PatchManagement.PatchManagementRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The personalAccessTokens property</summary>
        public global::ControlR.ApiClient.Api.PersonalAccessTokens.PersonalAccessTokensRequestBuilder PersonalAccessTokens
        {
            get => new global::ControlR.ApiClient.Api.PersonalAccessTokens.PersonalAccessTokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plugins property</summary>
        public global::ControlR.ApiClient.Api.Plugins.PluginsRequestBuilder Plugins
        {
            get => new global::ControlR.ApiClient.Api.Plugins.PluginsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The publicRegistrationSettings property</summary>
        public global::ControlR.ApiClient.Api.PublicRegistrationSettings.PublicRegistrationSettingsRequestBuilder PublicRegistrationSettings
        {
            get => new global::ControlR.ApiClient.Api.PublicRegistrationSettings.PublicRegistrationSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::ControlR.ApiClient.Api.Roles.RolesRequestBuilder Roles
        {
            get => new global::ControlR.ApiClient.Api.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scheduledTasks property</summary>
        public global::ControlR.ApiClient.Api.ScheduledTasks.ScheduledTasksRequestBuilder ScheduledTasks
        {
            get => new global::ControlR.ApiClient.Api.ScheduledTasks.ScheduledTasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scriptExecutions property</summary>
        public global::ControlR.ApiClient.Api.ScriptExecutions.ScriptExecutionsRequestBuilder ScriptExecutions
        {
            get => new global::ControlR.ApiClient.Api.ScriptExecutions.ScriptExecutionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scripts property</summary>
        public global::ControlR.ApiClient.Api.Scripts.ScriptsRequestBuilder Scripts
        {
            get => new global::ControlR.ApiClient.Api.Scripts.ScriptsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serverAlert property</summary>
        public global::ControlR.ApiClient.Api.ServerAlert.ServerAlertRequestBuilder ServerAlert
        {
            get => new global::ControlR.ApiClient.Api.ServerAlert.ServerAlertRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serverLogs property</summary>
        public global::ControlR.ApiClient.Api.ServerLogs.ServerLogsRequestBuilder ServerLogs
        {
            get => new global::ControlR.ApiClient.Api.ServerLogs.ServerLogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serverStats property</summary>
        public global::ControlR.ApiClient.Api.ServerStats.ServerStatsRequestBuilder ServerStats
        {
            get => new global::ControlR.ApiClient.Api.ServerStats.ServerStatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessionRecordings property</summary>
        public global::ControlR.ApiClient.Api.SessionRecordings.SessionRecordingsRequestBuilder SessionRecordings
        {
            get => new global::ControlR.ApiClient.Api.SessionRecordings.SessionRecordingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The suggestions property</summary>
        public global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder Suggestions
        {
            get => new global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The supportSessions property</summary>
        public global::ControlR.ApiClient.Api.SupportSessions.SupportSessionsRequestBuilder SupportSessions
        {
            get => new global::ControlR.ApiClient.Api.SupportSessions.SupportSessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Tags property</summary>
        public global::ControlR.ApiClient.Api.Tags.TagsRequestBuilder Tags
        {
            get => new global::ControlR.ApiClient.Api.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Tenants property</summary>
        public global::ControlR.ApiClient.Api.Tenants.TenantsRequestBuilder Tenants
        {
            get => new global::ControlR.ApiClient.Api.Tenants.TenantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenantSettings property</summary>
        public global::ControlR.ApiClient.Api.TenantSettings.TenantSettingsRequestBuilder TenantSettings
        {
            get => new global::ControlR.ApiClient.Api.TenantSettings.TenantSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The testEmail property</summary>
        public global::ControlR.ApiClient.Api.TestEmail.TestEmailRequestBuilder TestEmail
        {
            get => new global::ControlR.ApiClient.Api.TestEmail.TestEmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ticketing property</summary>
        public global::ControlR.ApiClient.Api.Ticketing.TicketingRequestBuilder Ticketing
        {
            get => new global::ControlR.ApiClient.Api.Ticketing.TicketingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The toolbox property</summary>
        public global::ControlR.ApiClient.Api.Toolbox.ToolboxRequestBuilder Toolbox
        {
            get => new global::ControlR.ApiClient.Api.Toolbox.ToolboxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userPreferences property</summary>
        public global::ControlR.ApiClient.Api.UserPreferences.UserPreferencesRequestBuilder UserPreferences
        {
            get => new global::ControlR.ApiClient.Api.UserPreferences.UserPreferencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userRoles property</summary>
        public global::ControlR.ApiClient.Api.UserRoles.UserRolesRequestBuilder UserRoles
        {
            get => new global::ControlR.ApiClient.Api.UserRoles.UserRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Users property</summary>
        public global::ControlR.ApiClient.Api.Users.UsersRequestBuilder Users
        {
            get => new global::ControlR.ApiClient.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userServerSettings property</summary>
        public global::ControlR.ApiClient.Api.UserServerSettings.UserServerSettingsRequestBuilder UserServerSettings
        {
            get => new global::ControlR.ApiClient.Api.UserServerSettings.UserServerSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userTags property</summary>
        public global::ControlR.ApiClient.Api.UserTags.UserTagsRequestBuilder UserTags
        {
            get => new global::ControlR.ApiClient.Api.UserTags.UserTagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Version property</summary>
        public global::ControlR.ApiClient.Api.VersionNamespace.VersionRequestBuilder Version
        {
            get => new global::ControlR.ApiClient.Api.VersionNamespace.VersionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::ControlR.ApiClient.Api.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::ControlR.ApiClient.Api.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
