// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.ClientPortal.Assignments;
using ControlR.ApiClient.Api.ClientPortal.Devices;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.ClientPortal
{
    /// <summary>
    /// Builds and executes requests for operations under \api\client-portal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientPortalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The assignments property</summary>
        public global::ControlR.ApiClient.Api.ClientPortal.Assignments.AssignmentsRequestBuilder Assignments
        {
            get => new global::ControlR.ApiClient.Api.ClientPortal.Assignments.AssignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::ControlR.ApiClient.Api.ClientPortal.Devices.DevicesRequestBuilder Devices
        {
            get => new global::ControlR.ApiClient.Api.ClientPortal.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ClientPortal.ClientPortalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientPortalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/client-portal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ClientPortal.ClientPortalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientPortalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/client-portal", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
