// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.Tenants.Devices.Item.Tenant;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.Tenants.Devices.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Tenants\devices\{deviceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDeviceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The tenant property</summary>
        public global::ControlR.ApiClient.Api.Tenants.Devices.Item.Tenant.TenantRequestBuilder Tenant
        {
            get => new global::ControlR.ApiClient.Api.Tenants.Devices.Item.Tenant.TenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Tenants.Devices.Item.WithDeviceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeviceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Tenants/devices/{deviceId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Tenants.Devices.Item.WithDeviceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeviceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Tenants/devices/{deviceId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
