// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.AuditLogs.Export;
using ControlR.ApiClient.Api.AuditLogs.Item;
using ControlR.ApiClient.Api.AuditLogs.Search;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.AuditLogs
{
    /// <summary>
    /// Builds and executes requests for operations under \api\audit-logs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuditLogsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The export property</summary>
        public global::ControlR.ApiClient.Api.AuditLogs.Export.ExportRequestBuilder Export
        {
            get => new global::ControlR.ApiClient.Api.AuditLogs.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::ControlR.ApiClient.Api.AuditLogs.Search.SearchRequestBuilder Search
        {
            get => new global::ControlR.ApiClient.Api.AuditLogs.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ControlR.ApiClient.api.auditLogs.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.AuditLogs.Item.AuditLogsItemRequestBuilder"/></returns>
        public global::ControlR.ApiClient.Api.AuditLogs.Item.AuditLogsItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::ControlR.ApiClient.Api.AuditLogs.Item.AuditLogsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ControlR.ApiClient.api.auditLogs.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.AuditLogs.Item.AuditLogsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ControlR.ApiClient.Api.AuditLogs.Item.AuditLogsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::ControlR.ApiClient.Api.AuditLogs.Item.AuditLogsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.AuditLogs.AuditLogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuditLogsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/audit-logs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.AuditLogs.AuditLogsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuditLogsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/audit-logs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
