// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.Suggestions.Item;
using ControlR.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ControlR.ApiClient.Api.Suggestions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\suggestions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuggestionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ControlR.ApiClient.api.suggestions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.Suggestions.Item.WithSuggestionItemRequestBuilder"/></returns>
        public global::ControlR.ApiClient.Api.Suggestions.Item.WithSuggestionItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("suggestionId", position);
                return new global::ControlR.ApiClient.Api.Suggestions.Item.WithSuggestionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ControlR.ApiClient.api.suggestions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.Suggestions.Item.WithSuggestionItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ControlR.ApiClient.Api.Suggestions.Item.WithSuggestionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("suggestionId", position);
                return new global::ControlR.ApiClient.Api.Suggestions.Item.WithSuggestionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuggestionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/suggestions{?count*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuggestionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/suggestions{?count*,status*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::ControlR.ApiClient.Models.AutomationSuggestionDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::ControlR.ApiClient.Models.AutomationSuggestionDto>?> GetAsync(Action<RequestConfiguration<global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::ControlR.ApiClient.Models.AutomationSuggestionDto>> GetAsync(Action<RequestConfiguration<global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ControlR.ApiClient.Models.AutomationSuggestionDto>(requestInfo, global::ControlR.ApiClient.Models.AutomationSuggestionDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class SuggestionsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("count")]
            public int? Count { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SuggestionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ControlR.ApiClient.Api.Suggestions.SuggestionsRequestBuilder.SuggestionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
