// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.Ticketing.Integrations;
using ControlR.ApiClient.Api.Ticketing.Tickets;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.Ticketing
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ticketing
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TicketingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The integrations property</summary>
        public global::ControlR.ApiClient.Api.Ticketing.Integrations.IntegrationsRequestBuilder Integrations
        {
            get => new global::ControlR.ApiClient.Api.Ticketing.Integrations.IntegrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tickets property</summary>
        public global::ControlR.ApiClient.Api.Ticketing.Tickets.TicketsRequestBuilder Tickets
        {
            get => new global::ControlR.ApiClient.Api.Ticketing.Tickets.TicketsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Ticketing.TicketingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TicketingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticketing", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Ticketing.TicketingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TicketingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticketing", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
