// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.Alerts.Item.Acknowledge;
using ControlR.ApiClient.Api.Alerts.Item.Resolve;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.Alerts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\alerts\{alertId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAlertItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The acknowledge property</summary>
        public global::ControlR.ApiClient.Api.Alerts.Item.Acknowledge.AcknowledgeRequestBuilder Acknowledge
        {
            get => new global::ControlR.ApiClient.Api.Alerts.Item.Acknowledge.AcknowledgeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resolve property</summary>
        public global::ControlR.ApiClient.Api.Alerts.Item.Resolve.ResolveRequestBuilder Resolve
        {
            get => new global::ControlR.ApiClient.Api.Alerts.Item.Resolve.ResolveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Alerts.Item.WithAlertItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAlertItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/alerts/{alertId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Alerts.Item.WithAlertItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAlertItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/alerts/{alertId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
