// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AlertRuleDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creatorUserId property</summary>
        public Guid? CreatorUserId { get; set; }
        /// <summary>The duration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Duration { get; set; }
#nullable restore
#else
        public string Duration { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isEnabled property</summary>
        public bool? IsEnabled { get; set; }
        /// <summary>The metricType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetricType { get; set; }
#nullable restore
#else
        public string MetricType { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The notificationRecipients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotificationRecipients { get; set; }
#nullable restore
#else
        public string NotificationRecipients { get; set; }
#endif
        /// <summary>The operator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operator { get; set; }
#nullable restore
#else
        public string Operator { get; set; }
#endif
        /// <summary>The targetDeviceIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? TargetDeviceIds { get; set; }
#nullable restore
#else
        public List<Guid?> TargetDeviceIds { get; set; }
#endif
        /// <summary>The targetGroupIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? TargetGroupIds { get; set; }
#nullable restore
#else
        public List<Guid?> TargetGroupIds { get; set; }
#endif
        /// <summary>The thresholdValue property</summary>
        public double? ThresholdValue { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.AlertRuleDto"/> and sets the default values.
        /// </summary>
        public AlertRuleDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.AlertRuleDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.AlertRuleDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.AlertRuleDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creatorUserId", n => { CreatorUserId = n.GetGuidValue(); } },
                { "duration", n => { Duration = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isEnabled", n => { IsEnabled = n.GetBoolValue(); } },
                { "metricType", n => { MetricType = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notificationRecipients", n => { NotificationRecipients = n.GetStringValue(); } },
                { "operator", n => { Operator = n.GetStringValue(); } },
                { "targetDeviceIds", n => { TargetDeviceIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "targetGroupIds", n => { TargetGroupIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "thresholdValue", n => { ThresholdValue = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("creatorUserId", CreatorUserId);
            writer.WriteStringValue("duration", Duration);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isEnabled", IsEnabled);
            writer.WriteStringValue("metricType", MetricType);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("notificationRecipients", NotificationRecipients);
            writer.WriteStringValue("operator", Operator);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("targetDeviceIds", TargetDeviceIds);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("targetGroupIds", TargetGroupIds);
            writer.WriteDoubleValue("thresholdValue", ThresholdValue);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
