// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuditLogDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>The actorUserId property</summary>
        public Guid? ActorUserId { get; set; }
        /// <summary>The actorUserName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActorUserName { get; set; }
#nullable restore
#else
        public string ActorUserName { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Details { get; set; }
#nullable restore
#else
        public string Details { get; set; }
#endif
        /// <summary>The duration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Duration { get; set; }
#nullable restore
#else
        public string Duration { get; set; }
#endif
        /// <summary>The endTimestamp property</summary>
        public DateTimeOffset? EndTimestamp { get; set; }
        /// <summary>The eventType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventType { get; set; }
#nullable restore
#else
        public string EventType { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The sessionId property</summary>
        public Guid? SessionId { get; set; }
        /// <summary>The sourceIpAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceIpAddress { get; set; }
#nullable restore
#else
        public string SourceIpAddress { get; set; }
#endif
        /// <summary>The targetDeviceId property</summary>
        public Guid? TargetDeviceId { get; set; }
        /// <summary>The targetDeviceName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetDeviceName { get; set; }
#nullable restore
#else
        public string TargetDeviceName { get; set; }
#endif
        /// <summary>The timestamp property</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.AuditLogDto"/> and sets the default values.
        /// </summary>
        public AuditLogDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.AuditLogDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.AuditLogDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.AuditLogDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "actorUserId", n => { ActorUserId = n.GetGuidValue(); } },
                { "actorUserName", n => { ActorUserName = n.GetStringValue(); } },
                { "details", n => { Details = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetStringValue(); } },
                { "endTimestamp", n => { EndTimestamp = n.GetDateTimeOffsetValue(); } },
                { "eventType", n => { EventType = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "sessionId", n => { SessionId = n.GetGuidValue(); } },
                { "sourceIpAddress", n => { SourceIpAddress = n.GetStringValue(); } },
                { "targetDeviceId", n => { TargetDeviceId = n.GetGuidValue(); } },
                { "targetDeviceName", n => { TargetDeviceName = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteGuidValue("actorUserId", ActorUserId);
            writer.WriteStringValue("actorUserName", ActorUserName);
            writer.WriteStringValue("details", Details);
            writer.WriteStringValue("duration", Duration);
            writer.WriteDateTimeOffsetValue("endTimestamp", EndTimestamp);
            writer.WriteStringValue("eventType", EventType);
            writer.WriteGuidValue("id", Id);
            writer.WriteGuidValue("sessionId", SessionId);
            writer.WriteStringValue("sourceIpAddress", SourceIpAddress);
            writer.WriteGuidValue("targetDeviceId", TargetDeviceId);
            writer.WriteStringValue("targetDeviceName", TargetDeviceName);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
