// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuditLogSearchRequestDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actorUserName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActorUserName { get; set; }
#nullable restore
#else
        public string ActorUserName { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The endDate property</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>The eventType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventType { get; set; }
#nullable restore
#else
        public string EventType { get; set; }
#endif
        /// <summary>The searchText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchText { get; set; }
#nullable restore
#else
        public string SearchText { get; set; }
#endif
        /// <summary>The skip property</summary>
        public int? Skip { get; set; }
        /// <summary>The startDate property</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>The take property</summary>
        public int? Take { get; set; }
        /// <summary>The targetDeviceId property</summary>
        public Guid? TargetDeviceId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.AuditLogSearchRequestDto"/> and sets the default values.
        /// </summary>
        public AuditLogSearchRequestDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.AuditLogSearchRequestDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.AuditLogSearchRequestDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.AuditLogSearchRequestDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actorUserName", n => { ActorUserName = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetDateTimeOffsetValue(); } },
                { "eventType", n => { EventType = n.GetStringValue(); } },
                { "searchText", n => { SearchText = n.GetStringValue(); } },
                { "skip", n => { Skip = n.GetIntValue(); } },
                { "startDate", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "take", n => { Take = n.GetIntValue(); } },
                { "targetDeviceId", n => { TargetDeviceId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("actorUserName", ActorUserName);
            writer.WriteDateTimeOffsetValue("endDate", EndDate);
            writer.WriteStringValue("eventType", EventType);
            writer.WriteStringValue("searchText", SearchText);
            writer.WriteIntValue("skip", Skip);
            writer.WriteDateTimeOffsetValue("startDate", StartDate);
            writer.WriteIntValue("take", Take);
            writer.WriteGuidValue("targetDeviceId", TargetDeviceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
