// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchInstallationDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The completedAt property</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The deviceId property</summary>
        public Guid? DeviceId { get; set; }
        /// <summary>The failedCount property</summary>
        public int? FailedCount { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The initiatedAt property</summary>
        public DateTimeOffset? InitiatedAt { get; set; }
        /// <summary>The initiatedByUserId property</summary>
        public Guid? InitiatedByUserId { get; set; }
        /// <summary>The installedCount property</summary>
        public int? InstalledCount { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The totalCount property</summary>
        public int? TotalCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.PatchInstallationDto"/> and sets the default values.
        /// </summary>
        public PatchInstallationDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.PatchInstallationDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.PatchInstallationDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.PatchInstallationDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "deviceId", n => { DeviceId = n.GetGuidValue(); } },
                { "failedCount", n => { FailedCount = n.GetIntValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "initiatedAt", n => { InitiatedAt = n.GetDateTimeOffsetValue(); } },
                { "initiatedByUserId", n => { InitiatedByUserId = n.GetGuidValue(); } },
                { "installedCount", n => { InstalledCount = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteGuidValue("deviceId", DeviceId);
            writer.WriteIntValue("failedCount", FailedCount);
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("initiatedAt", InitiatedAt);
            writer.WriteGuidValue("initiatedByUserId", InitiatedByUserId);
            writer.WriteIntValue("installedCount", InstalledCount);
            writer.WriteStringValue("status", Status);
            writer.WriteIntValue("totalCount", TotalCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
