// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PendingPatchDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The detectedAt property</summary>
        public DateTimeOffset? DetectedAt { get; set; }
        /// <summary>The deviceId property</summary>
        public Guid? DeviceId { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The installedAt property</summary>
        public DateTimeOffset? InstalledAt { get; set; }
        /// <summary>The isCritical property</summary>
        public bool? IsCritical { get; set; }
        /// <summary>The isImportant property</summary>
        public bool? IsImportant { get; set; }
        /// <summary>The sizeBytes property</summary>
        public long? SizeBytes { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The updateId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateId { get; set; }
#nullable restore
#else
        public string UpdateId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.PendingPatchDto"/> and sets the default values.
        /// </summary>
        public PendingPatchDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.PendingPatchDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.PendingPatchDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.PendingPatchDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "detectedAt", n => { DetectedAt = n.GetDateTimeOffsetValue(); } },
                { "deviceId", n => { DeviceId = n.GetGuidValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "installedAt", n => { InstalledAt = n.GetDateTimeOffsetValue(); } },
                { "isCritical", n => { IsCritical = n.GetBoolValue(); } },
                { "isImportant", n => { IsImportant = n.GetBoolValue(); } },
                { "sizeBytes", n => { SizeBytes = n.GetLongValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updateId", n => { UpdateId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("detectedAt", DetectedAt);
            writer.WriteGuidValue("deviceId", DeviceId);
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("installedAt", InstalledAt);
            writer.WriteBoolValue("isCritical", IsCritical);
            writer.WriteBoolValue("isImportant", IsImportant);
            writer.WriteLongValue("sizeBytes", SizeBytes);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("updateId", UpdateId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
