// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProvisionTenantResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The adminEmail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdminEmail { get; set; }
#nullable restore
#else
        public string AdminEmail { get; set; }
#endif
        /// <summary>The patCreated property</summary>
        public bool? PatCreated { get; set; }
        /// <summary>The personalAccessToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonalAccessToken { get; set; }
#nullable restore
#else
        public string PersonalAccessToken { get; set; }
#endif
        /// <summary>The tenantCreated property</summary>
        public bool? TenantCreated { get; set; }
        /// <summary>The tenantId property</summary>
        public Guid? TenantId { get; set; }
        /// <summary>The tenantName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantName { get; set; }
#nullable restore
#else
        public string TenantName { get; set; }
#endif
        /// <summary>The userCreated property</summary>
        public bool? UserCreated { get; set; }
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.ProvisionTenantResponseDto"/> and sets the default values.
        /// </summary>
        public ProvisionTenantResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.ProvisionTenantResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.ProvisionTenantResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.ProvisionTenantResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adminEmail", n => { AdminEmail = n.GetStringValue(); } },
                { "patCreated", n => { PatCreated = n.GetBoolValue(); } },
                { "personalAccessToken", n => { PersonalAccessToken = n.GetStringValue(); } },
                { "tenantCreated", n => { TenantCreated = n.GetBoolValue(); } },
                { "tenantId", n => { TenantId = n.GetGuidValue(); } },
                { "tenantName", n => { TenantName = n.GetStringValue(); } },
                { "userCreated", n => { UserCreated = n.GetBoolValue(); } },
                { "userId", n => { UserId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("adminEmail", AdminEmail);
            writer.WriteBoolValue("patCreated", PatCreated);
            writer.WriteStringValue("personalAccessToken", PersonalAccessToken);
            writer.WriteBoolValue("tenantCreated", TenantCreated);
            writer.WriteGuidValue("tenantId", TenantId);
            writer.WriteStringValue("tenantName", TenantName);
            writer.WriteBoolValue("userCreated", UserCreated);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
