// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScriptExecutionDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The completedAt property</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The initiatedByUserId property</summary>
        public Guid? InitiatedByUserId { get; set; }
        /// <summary>The results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ControlR.ApiClient.Models.ScriptExecutionResultDto>? Results { get; set; }
#nullable restore
#else
        public List<global::ControlR.ApiClient.Models.ScriptExecutionResultDto> Results { get; set; }
#endif
        /// <summary>The scriptId property</summary>
        public Guid? ScriptId { get; set; }
        /// <summary>The scriptName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScriptName { get; set; }
#nullable restore
#else
        public string ScriptName { get; set; }
#endif
        /// <summary>The scriptType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScriptType { get; set; }
#nullable restore
#else
        public string ScriptType { get; set; }
#endif
        /// <summary>The startedAt property</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.ScriptExecutionDto"/> and sets the default values.
        /// </summary>
        public ScriptExecutionDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.ScriptExecutionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.ScriptExecutionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.ScriptExecutionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "initiatedByUserId", n => { InitiatedByUserId = n.GetGuidValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::ControlR.ApiClient.Models.ScriptExecutionResultDto>(global::ControlR.ApiClient.Models.ScriptExecutionResultDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "scriptId", n => { ScriptId = n.GetGuidValue(); } },
                { "scriptName", n => { ScriptName = n.GetStringValue(); } },
                { "scriptType", n => { ScriptType = n.GetStringValue(); } },
                { "startedAt", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteGuidValue("initiatedByUserId", InitiatedByUserId);
            writer.WriteCollectionOfObjectValues<global::ControlR.ApiClient.Models.ScriptExecutionResultDto>("results", Results);
            writer.WriteGuidValue("scriptId", ScriptId);
            writer.WriteStringValue("scriptName", ScriptName);
            writer.WriteStringValue("scriptType", ScriptType);
            writer.WriteDateTimeOffsetValue("startedAt", StartedAt);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
