// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SessionRecordingDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The deviceId property</summary>
        public Guid? DeviceId { get; set; }
        /// <summary>The deviceName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceName { get; set; }
#nullable restore
#else
        public string DeviceName { get; set; }
#endif
        /// <summary>The durationMs property</summary>
        public long? DurationMs { get; set; }
        /// <summary>The frameCount property</summary>
        public int? FrameCount { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The recorderUserId property</summary>
        public Guid? RecorderUserId { get; set; }
        /// <summary>The recorderUserName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecorderUserName { get; set; }
#nullable restore
#else
        public string RecorderUserName { get; set; }
#endif
        /// <summary>The sessionEndedAt property</summary>
        public DateTimeOffset? SessionEndedAt { get; set; }
        /// <summary>The sessionId property</summary>
        public Guid? SessionId { get; set; }
        /// <summary>The sessionStartedAt property</summary>
        public DateTimeOffset? SessionStartedAt { get; set; }
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>The storageSizeBytes property</summary>
        public long? StorageSizeBytes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.SessionRecordingDto"/> and sets the default values.
        /// </summary>
        public SessionRecordingDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.SessionRecordingDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.SessionRecordingDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.SessionRecordingDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "deviceId", n => { DeviceId = n.GetGuidValue(); } },
                { "deviceName", n => { DeviceName = n.GetStringValue(); } },
                { "durationMs", n => { DurationMs = n.GetLongValue(); } },
                { "frameCount", n => { FrameCount = n.GetIntValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "recorderUserId", n => { RecorderUserId = n.GetGuidValue(); } },
                { "recorderUserName", n => { RecorderUserName = n.GetStringValue(); } },
                { "sessionEndedAt", n => { SessionEndedAt = n.GetDateTimeOffsetValue(); } },
                { "sessionId", n => { SessionId = n.GetGuidValue(); } },
                { "sessionStartedAt", n => { SessionStartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "storageSizeBytes", n => { StorageSizeBytes = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteGuidValue("deviceId", DeviceId);
            writer.WriteStringValue("deviceName", DeviceName);
            writer.WriteLongValue("durationMs", DurationMs);
            writer.WriteIntValue("frameCount", FrameCount);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("notes", Notes);
            writer.WriteGuidValue("recorderUserId", RecorderUserId);
            writer.WriteStringValue("recorderUserName", RecorderUserName);
            writer.WriteDateTimeOffsetValue("sessionEndedAt", SessionEndedAt);
            writer.WriteGuidValue("sessionId", SessionId);
            writer.WriteDateTimeOffsetValue("sessionStartedAt", SessionStartedAt);
            writer.WriteIntValue("status", Status);
            writer.WriteLongValue("storageSizeBytes", StorageSizeBytes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
