// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SupportSessionDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessCode { get; set; }
#nullable restore
#else
        public string AccessCode { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The clientEmail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientEmail { get; set; }
#nullable restore
#else
        public string ClientEmail { get; set; }
#endif
        /// <summary>The clientName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientName { get; set; }
#nullable restore
#else
        public string ClientName { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The creatorUserId property</summary>
        public Guid? CreatorUserId { get; set; }
        /// <summary>The creatorUserName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorUserName { get; set; }
#nullable restore
#else
        public string CreatorUserName { get; set; }
#endif
        /// <summary>The deviceId property</summary>
        public Guid? DeviceId { get; set; }
        /// <summary>The deviceName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceName { get; set; }
#nullable restore
#else
        public string DeviceName { get; set; }
#endif
        /// <summary>The expiresAt property</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isUsed property</summary>
        public bool? IsUsed { get; set; }
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The sessionEndedAt property</summary>
        public DateTimeOffset? SessionEndedAt { get; set; }
        /// <summary>The sessionStartedAt property</summary>
        public DateTimeOffset? SessionStartedAt { get; set; }
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.SupportSessionDto"/> and sets the default values.
        /// </summary>
        public SupportSessionDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.SupportSessionDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.SupportSessionDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.SupportSessionDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessCode", n => { AccessCode = n.GetStringValue(); } },
                { "clientEmail", n => { ClientEmail = n.GetStringValue(); } },
                { "clientName", n => { ClientName = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "creatorUserId", n => { CreatorUserId = n.GetGuidValue(); } },
                { "creatorUserName", n => { CreatorUserName = n.GetStringValue(); } },
                { "deviceId", n => { DeviceId = n.GetGuidValue(); } },
                { "deviceName", n => { DeviceName = n.GetStringValue(); } },
                { "expiresAt", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isUsed", n => { IsUsed = n.GetBoolValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "sessionEndedAt", n => { SessionEndedAt = n.GetDateTimeOffsetValue(); } },
                { "sessionStartedAt", n => { SessionStartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accessCode", AccessCode);
            writer.WriteStringValue("clientEmail", ClientEmail);
            writer.WriteStringValue("clientName", ClientName);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteGuidValue("creatorUserId", CreatorUserId);
            writer.WriteStringValue("creatorUserName", CreatorUserName);
            writer.WriteGuidValue("deviceId", DeviceId);
            writer.WriteStringValue("deviceName", DeviceName);
            writer.WriteDateTimeOffsetValue("expiresAt", ExpiresAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isUsed", IsUsed);
            writer.WriteStringValue("notes", Notes);
            writer.WriteDateTimeOffsetValue("sessionEndedAt", SessionEndedAt);
            writer.WriteDateTimeOffsetValue("sessionStartedAt", SessionStartedAt);
            writer.WriteIntValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
