// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SupportSessionJoinResponseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The serverUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerUrl { get; set; }
#nullable restore
#else
        public string ServerUrl { get; set; }
#endif
        /// <summary>The sessionId property</summary>
        public Guid? SessionId { get; set; }
        /// <summary>The technicianName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TechnicianName { get; set; }
#nullable restore
#else
        public string TechnicianName { get; set; }
#endif
        /// <summary>The tenantId property</summary>
        public Guid? TenantId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.SupportSessionJoinResponseDto"/> and sets the default values.
        /// </summary>
        public SupportSessionJoinResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.SupportSessionJoinResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.SupportSessionJoinResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.SupportSessionJoinResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "serverUrl", n => { ServerUrl = n.GetStringValue(); } },
                { "sessionId", n => { SessionId = n.GetGuidValue(); } },
                { "technicianName", n => { TechnicianName = n.GetStringValue(); } },
                { "tenantId", n => { TenantId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("serverUrl", ServerUrl);
            writer.WriteGuidValue("sessionId", SessionId);
            writer.WriteStringValue("technicianName", TechnicianName);
            writer.WriteGuidValue("tenantId", TenantId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
