// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ControlR.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TicketLinkDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alertId property</summary>
        public Guid? AlertId { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The createdByUserId property</summary>
        public Guid? CreatedByUserId { get; set; }
        /// <summary>The deviceId property</summary>
        public Guid? DeviceId { get; set; }
        /// <summary>The externalTicketId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalTicketId { get; set; }
#nullable restore
#else
        public string ExternalTicketId { get; set; }
#endif
        /// <summary>The externalTicketUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalTicketUrl { get; set; }
#nullable restore
#else
        public string ExternalTicketUrl { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The provider property</summary>
        public int? Provider { get; set; }
        /// <summary>The sessionId property</summary>
        public Guid? SessionId { get; set; }
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Models.TicketLinkDto"/> and sets the default values.
        /// </summary>
        public TicketLinkDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Models.TicketLinkDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ControlR.ApiClient.Models.TicketLinkDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ControlR.ApiClient.Models.TicketLinkDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alertId", n => { AlertId = n.GetGuidValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetGuidValue(); } },
                { "deviceId", n => { DeviceId = n.GetGuidValue(); } },
                { "externalTicketId", n => { ExternalTicketId = n.GetStringValue(); } },
                { "externalTicketUrl", n => { ExternalTicketUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "provider", n => { Provider = n.GetIntValue(); } },
                { "sessionId", n => { SessionId = n.GetGuidValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("alertId", AlertId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteGuidValue("createdByUserId", CreatedByUserId);
            writer.WriteGuidValue("deviceId", DeviceId);
            writer.WriteStringValue("externalTicketId", ExternalTicketId);
            writer.WriteStringValue("externalTicketUrl", ExternalTicketUrl);
            writer.WriteGuidValue("id", Id);
            writer.WriteIntValue("provider", Provider);
            writer.WriteGuidValue("sessionId", SessionId);
            writer.WriteStringValue("subject", Subject);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
