// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.PatchManagement.Install;
using ControlR.ApiClient.Api.PatchManagement.Installations;
using ControlR.ApiClient.Api.PatchManagement.Pending;
using ControlR.ApiClient.Api.PatchManagement.Scan;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.PatchManagement
{
    /// <summary>
    /// Builds and executes requests for operations under \api\patch-management
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatchManagementRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The install property</summary>
        public global::ControlR.ApiClient.Api.PatchManagement.Install.InstallRequestBuilder Install
        {
            get => new global::ControlR.ApiClient.Api.PatchManagement.Install.InstallRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installations property</summary>
        public global::ControlR.ApiClient.Api.PatchManagement.Installations.InstallationsRequestBuilder Installations
        {
            get => new global::ControlR.ApiClient.Api.PatchManagement.Installations.InstallationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pending property</summary>
        public global::ControlR.ApiClient.Api.PatchManagement.Pending.PendingRequestBuilder Pending
        {
            get => new global::ControlR.ApiClient.Api.PatchManagement.Pending.PendingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scan property</summary>
        public global::ControlR.ApiClient.Api.PatchManagement.Scan.ScanRequestBuilder Scan
        {
            get => new global::ControlR.ApiClient.Api.PatchManagement.Scan.ScanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.PatchManagement.PatchManagementRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PatchManagementRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/patch-management", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.PatchManagement.PatchManagementRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PatchManagementRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/patch-management", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
