// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.ActionVerification.Status;
using ControlR.ApiClient.Api.ActionVerification.Verify;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.ActionVerification
{
    /// <summary>
    /// Builds and executes requests for operations under \api\action-verification
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActionVerificationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The status property</summary>
        public global::ControlR.ApiClient.Api.ActionVerification.Status.StatusRequestBuilder Status
        {
            get => new global::ControlR.ApiClient.Api.ActionVerification.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verify property</summary>
        public global::ControlR.ApiClient.Api.ActionVerification.Verify.VerifyRequestBuilder Verify
        {
            get => new global::ControlR.ApiClient.Api.ActionVerification.Verify.VerifyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ActionVerification.ActionVerificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionVerificationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/action-verification", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ActionVerification.ActionVerificationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionVerificationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/action-verification", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
