// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ControlR.ApiClient.Api.ScheduledTasks.Item.Executions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\scheduled-tasks\{taskId}\executions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecutionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecutionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/scheduled-tasks/{taskId}/executions{?count*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecutionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/scheduled-tasks/{taskId}/executions{?count*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::ControlR.ApiClient.Models.ScheduledTaskExecutionDto&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::ControlR.ApiClient.Models.ScheduledTaskExecutionDto>?> GetAsync(Action<RequestConfiguration<global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::ControlR.ApiClient.Models.ScheduledTaskExecutionDto>> GetAsync(Action<RequestConfiguration<global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ControlR.ApiClient.Models.ScheduledTaskExecutionDto>(requestInfo, global::ControlR.ApiClient.Models.ScheduledTaskExecutionDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ExecutionsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("count")]
            public int? Count { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecutionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ControlR.ApiClient.Api.ScheduledTasks.Item.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
