// <auto-generated/>
#pragma warning disable CS0618
using ControlR.ApiClient.Api.Inventory.Item.Hardware;
using ControlR.ApiClient.Api.Inventory.Item.Software;
using ControlR.ApiClient.Api.Inventory.Item.Updates;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ControlR.ApiClient.Api.Inventory.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\inventory\{deviceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDeviceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The hardware property</summary>
        public global::ControlR.ApiClient.Api.Inventory.Item.Hardware.HardwareRequestBuilder Hardware
        {
            get => new global::ControlR.ApiClient.Api.Inventory.Item.Hardware.HardwareRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The software property</summary>
        public global::ControlR.ApiClient.Api.Inventory.Item.Software.SoftwareRequestBuilder Software
        {
            get => new global::ControlR.ApiClient.Api.Inventory.Item.Software.SoftwareRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updates property</summary>
        public global::ControlR.ApiClient.Api.Inventory.Item.Updates.UpdatesRequestBuilder Updates
        {
            get => new global::ControlR.ApiClient.Api.Inventory.Item.Updates.UpdatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Inventory.Item.WithDeviceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeviceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/inventory/{deviceId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ControlR.ApiClient.Api.Inventory.Item.WithDeviceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeviceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/inventory/{deviceId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
